name: backendTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd ./amplify/backend/function/kinetikSimulationLambda/src && pip3 install numpy && python -m unittest backendTest.py
